'use strict';

/**
 * @ngdoc function
 * @name poluxClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the poluxClienteApp
 */
var text_es = {
    TITULO: "GENERATOR-OAS",
    MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
    EVALUAR_PROYECTO: "Evaluación de Proyecto de Grado",
    LISTADO_SOLICITUD: "Listado de Solicitudes",
    MODALIDAD: "Modalidad",
    TITULO_PROPUESTA: "Título de la propuesta",
    VER_DOCUMENTO: "Ver documento",
    ESTADO_DOCUMENTO: "Estado Documento",
    RESUMEN: "Resumen",
    OPCIONES: "Opciones",
    SOLICITUD: "Solicitud",
    DOCENTE: "Docente",
    SELECCION_DOCENTE: "Seleccione Docente",
    SELECCION_TIPO_VINCULACION: "Seleccione el tipo de vinculación",
    TIPO_VINCULACION: "Tipo de vinculación",
    ASIGNAR_DOCENTE: "Asignar Docente",
    SOCIALIZACION: "Socialización de proyectos de grado",
    AREAS_TRABAJO_GRADO: "Areas trabajo de Grado",
    DOCENTES_ASIGNADOS: "Docentes Asignados",
    VER_TODOS: "Ver Todos",
    VER_SUGERENCIAS: "Ver Sugerencias",
    NUEVA_EVALUACION: "Nueva Evaluación",
    FORMATOS_EVALUACION: "Formatos de Evaluación",
    BUSCAR_FORMATOS: "Buscar Formatos",
    FECHA: "Fecha",
    HORA: "Hora",
    SELECCION_PROYECTO: "Seleccione el Proyecto",
    LUGAR: "Lugar",
    SELECCIONE_FORMATO: "Seleccione el formato",
    AREAS_CONOCIMIENTO: "Áreas de Conocimiento",
    LISTAR_SOLICITUDES: "Listado de solicitudes",
    ANO: "Año",
    PERIODO: "Periodo",
    CARRERA: "Carrera",
    POSGRADO: "Posgrado",
    CODIGO_POSGRADO: "Código del posgrado",
    CODIGO_ESP_ACADEMICO: "Código del espacio académico",
    PENSUM: "Pensum",
    CODIGO_PENSUM_POSGRADO: "Código del pensum publicado para el posgrado",
    SELECCIONAR_CARRERA: "Seleccione la carrera",
    SELECCIONAR_PENSUM: "*Seleccione un pensum",
    CODIGO: "Código",
    NOMBRE: "Nombre",
    NOMBRE_ESP_ACADEMICO: "Nombre del espacio académico",
    ESP_ACADEMICOS: "Espacios académicos",
    MODALIDAD_ESP_POS: "Modalidad: Espacios académicos de posgrado",
    MODALIDAD_ESP_PROFUNDIZACION: "Modalidad: Espacios académicos de profundización",
    ADMITIDOS_POR_RENDIMIENTO: "Admitidos por rendimiento:",
    ADMITIDOS_POR_ECONOMIA: "Admitidos por pago:",
    FECHA_ACTUAL: "Fecha actual:",
    FECHA_INICIO_UNO: "Primera fecha de inicio:",
    FECHA_INICIO_DOS: "Segunda fecha de inicio:",
    FECHA_FIN: "Fecha de finalización:",
    SELECCION_DE_ADMITIDOS: "Selección de Admitidos",
    ADMITIDOS_POR_EXCELENCIA_A: "Admitidos por excelencia académica y exentos de pago (Máx",
    ADMITIDOS_POR_COND_EC: "Admitidos admitidos por condiciones económicas y calidades académicas (Máx ",
    REQUERIDO: "Es requerido",
    PUBLICACION_DE_ESPACIOS: "Publicación de espacios académicos.",
    RESPUESTA: "Respuesta:",
    DENEGADO: "El estudiante no cumple con los requisitos exigidos para la Modalidad de Trabajo de Grado",
    REGISTRAR_PROPUESTA: "Registrar propuesta.",
    ESTADO: "Estado:",
    ESTADO_SIN_DOSPUNTOS: "Estado",
    PORCENTAJE_CURSADO: "Porcentaje cursado",
    PROMEDIO: "Promedio",
    RENDIMIENTO: "Rendimiento académico",
    NIVEL_ESTUDIOS: "Nivel de estudios:",
    TIPO_CARRERA: "Tipo de carrera",
    REGISTRAR_TRABAJO_DE_GRADO: "Registrar trabajo de grado.",
    EDICION_FORMATO_EVALUACION: "Edición de Formatos de Evaluación",
    SELECCIONAR_FORMATO: "Seleccionar Formato:",
    EDICION_GENERAL: "Edición general",
    TITULO_FORMATO: "Titulo Formato:",
    INTRODUCCION: "Introducción:",
    EDICION_PREGUNTAS: "Edición Preguntas",
    ENUNCIADO: "Enunciado:",
    PESO: "Peso:",
    TIPO: "Tipo:",
    NOMBRE_FORMATO: "Nombre del formato",
    INTRODUCCION_FORMATO: "Introducción del formato",
    ANADIR_PREGUNTA: "Añadir Pregunta",
    ANADIR_OPCION: "Añadir Opción",
    VISTA_PREVIA: "Vista Previa",
    ASIGNAR_FORMATO_A_PC: "Asignar formato a proyecto curricular:",
    ASOCIAR_FORMATO_A_PC: "Asociar formato a proyecto curricular:",
    SELECCIONAR_PC: "Seleccionar proyecto curricular:",
    CREACION_EVALUACION: "Creación de la evaluación",
    REVISION_DOCUMENTOS: "Revisión de Documentos",
    DOCUMENTO: "Documento",
    REVISIONES: "Revisiones",
    LA_REVISION: "La revisión ",
    LA_REVISION_SE_ENCUENTRA: " se encuentra solicitada ",
    SUBIR_DOCUMENTO: "Subir Documento",
    PUBLICAR_ASIGNATURA: "Publicar asignatura",
    SOLICITUDES_DEL_ESTUDIANTE: "Solicitudes del estudiante",
    NINGUNA_SOLICITUD_REALIZADA: "Ninguna solicitud realizada",
    SOLICITUD_NUM: "Solicitud N° ",
    FORMALIZACION: "Formalización: ",
    CREDITOS: "Créditos ",
    SEMESTRE: "Semestre ",
    ESTUDIANTE_ACTUAL: "Estudiante actual: ",
    TITULO_TG: "Título del trabajo de grado",
    ASIGNAR_AREA: "Asignar Área",
    DE_ACUERDO_A_SU_PROPUESTA: "De acuerdo a su propuesta, seleccione las áreas, luego adjunte el archivo del documento",
    ESTUDIANTE: "Estudiante",
    NOMBRE_PROPUESTA: "Nombre de la propuesta",
    DE_ACUERDO_A_SU_PROPUEST: "De acuerdo a su propuesta seleccione las áreas",
    SELECCIONE_LAS_OPCIONES: "Seleccione las opciones para vincular el docente",
    FILTRANDO_POR: "Filtrando por: ",
    VINCULAR_DOCENTE: "Vincular docente",
    NOMBRE_DEL_DOCUMENTO: "Nombre del documento",
    SELECCIONE_EL_DOCUMENTO: "Seleccione el documento",
    CARGAR_ARCHIVO: "Cargar archivo",
    ARRASTRE_O_CLICK: "Arrastre el archivo o haga click para subir al servidor",
    GUARDAR_REGISTRO: "Guardar registro",
    CANCELAR: "Cancelar",
    BORRAR: "Borrar",
    CALIFICACION_FINAL_PG: "Calificación Final del proyecto de grado",
    ENVIAR_EVALUACION: "Enviar Evaluación",
    FECHA_REVISION: "Fecha Revisión: ",
    REVISION: "Revisión ",
    INGRESE_NUEVA_AREA: "Ingrese una nueva área",
    NOMBRE_MUY_CORTO: "Nombre muy corto!",
    NOMBRE_MUY_EXTENSO: "Nombre muy largo!",
    DE_ACUERDO_A_SU_PERFIL: "De acuerdo a su perfil seleccione las áreas: ",
    EL_AREA_NO_EXISTE: "El área no existe",
    NO_EXISTEN_AREAS: "No existen áreas",
    AREAS_DOCENTE: "Áreas del docente",
    DOCENTE_ACTUAL: "Docente actual: ",
    GUARDAR: "Guardar",
    OPCION_BOTON: " + Opción",
    PREGUNTA_BOTON: " + Pregunta",
    ASIGNAR_BOTON: " Asignar",
    SEL_FECHA: "Seleccione una fecha",
    ENVIAR_EVALUACION_BOTON: "Enviar calificación",
    SOLICITAR_REVISION: "Solicitar Revision",
    SELECCIONAR: "Seleccionar",
    NUEVA_SOLICITUD: "Crear nueva solicitud",
    GESTION_SOLICITUD: "Módulo de gestión de solicitudes. ",
    SELECCIONAR_MODALIDAD:"Seleccione la modalidad",
    SELECCIONAR_SOLICITUD:"Seleccione tipo de solicitud",
    FORMULARIO_SOLICITUD:"Formulario de solicitud",
    SELECCIONE_AREAS_CONOCIMIENTO:"Seleccione las áreas del conocimiento de su proyecto",
    NOMBRE_CORTO:"Nombre muy corto",
    NOMBRE_LARGO:"Nombre muy largo",
    NUEVA_AREA:"Ingrese nueva area",
    TRABAJO_GRADO:"Trabajo de Grado",
    AGREGAR_ESTUDIANTES:"Agregar estudiantes a la solicitud",
    INGRESE_CODIGO:"Digite el código de los otros estudiantes que participan en el proyecto",
    ESTUDIANTE_EN_LISTA:"Error: El estudiante ya se encuentra en la lista de solicitados.",
    ESTUDIANTE_NO_VALIDO:"Error: El codigo digitado no es valido.",
    ESTUDIANTE_NO_REQUISITOS:"Error: El estudiante solicitado actualmente no cumple con los requisitos para realizar un trabajo de grado.",
    ESTUDIANTE_TRABAJO_GRADO:"Error: El estudiante solicitado actualmente esta realizando un trabajo de grado.",
    FALTAN_DATOS_ESTUDIANTE:"Error: No se encontraron datos del estudiante.",
    CANTIDAD_EXCEDIDA:"Error: Se excede la cantidad de estudiantes para la modalidad solicitada.",
    SOLICITAR_ASIGNATURAS:"Solicitar Asignaturas",
    ANIO:"Año",
    ERROR:"ERROR",
    NO_CARRERAS_POSGRADO:"Señor Coordinador, no tiene asignadas carreras con nivel de POSGRADO",
    NO_CARRERAS_PREGRADO:"Señor Coordinador, no tiene asignadas carreras con nivel de PREGRADO",
    NO_PENSUMS:"La carrera no tiene pensums activos",
    NO_ASIGNATURAS:"No hay espacios académicos pertenecientes al pensum seleccionado",
    NOMBRE_EMPRESA:"Escriba el nombre de la empresa",
    REGISTRO_FORMULARIO:"Registro de formulario",
    REGISTRO_PAGO:"Registro del pago",
    REGISTRO_NOTA:"Registro de las notas",
    SOLICITUD_REGISTRADA:"El formulario se registro correctamente",
    ERROR_CARGAR_SOLICITUDES:"Ocurrio un error al intentar cargar la solicitud",
    ERROR_SOLICITUDES_1:"Ocurrió un error al insertar los detalles de la solicitud",
    ERROR_SOLICITUDES_2:"Ocurrió un error al insertar los usuarios de la solicitud.",
    ERROR_SOLICITUDES_3:"Ocurrió un error al insertar la respuesta de la solicitud.",
    ERROR_RTA_SOLICITUD_1: "Ocurrió un error al actualizar la respuesta de la solicitud.",
    ERROR_RTA_SOLICITUD_2: "Ocurrió un error al registrar la respuesta de la solicitud.",
    ERROR_RTA_SOLICITUD_3: "Ocurrió un error al registrar el acta de respuesta de la solicitud.",
    ERROR_RTA_SOLICITUD_4: "Ocurrió un error al registrar el trabajo de grado.",
    ERROR_RTA_SOLICITUD_5: "Ocurrió un error al registrar la vinculación de trabajo de grado.",
    ERROR_RTA_SOLICITUD_6: "Ocurrió un error al actualizar la vinculación de trabajo de grado.",
    ERROR_RTA_SOLICITUD_7: "Ocurrió un error al actualizar el estado del estudiante en el trabajo de grado.",
    ERROR_RTA_SOLICITUD_8: "Error al cancelar el trabajo de grado.",
    ERROR_RTA_SOLICITUD_9: "Ocurrió un error al registrar el estudiante en el trabajo de grado.",
    ERROR_RTA_SOLICITUD_10: "Ocurrió un error al registrar las áreas de conocimiento del trabajo de grado.",
    ERROR_RTA_SOLICITUD_11: "Ocurrió un error al registrar el documento de la propuesta de trabajo de grado.",
    ERROR_RTA_SOLICITUD_12: "Ocurrió un error al asociar el documento escrito a la propuesta de trabajo de grado.",
    ERROR_RTA_SOLICITUD_13: "Ocurrió un error al actualizar el trabajo de grado.",
    ERROR: {
        SUBIR_DOCUMENTO:"Error al intentar subir un documento.",
        CARGAR_DOCUMENTO:"Ocurrio un error al cargar los documentos, por favor verifique su conexión e intente de nuevo.",
        HAY_SOLICITUD_DISTINCION:"Actualmente ya hay una solicitud de distinción pendiente para este trabajo de grado.",
        HAY_SOLICITUD_PENDIENTE:"Actualmente el estudiante ya tiene registrada una solicitud de trabajo de grado que se encuentra pendiente por respuesta.",
        DOCENTE_DUPLICADO:"Por favor seleccione docentes diferentes en los campos de director y evaluador(es).",
        CARGA_SOLICITUDES:"Error al cargar las solicitudes.",
        ENVIO_SOLICITUD:"Error al enviar la solicitud.",
        NO_AREAS_CARGADAS:"Error al intentar cargar las áreas de conocimiento.",
        NO_NUCLEOS_CARGADOS:"Error al intentar cargar los núcles básicos.",
        NO_EXISTE_ESTUDIANTE_POSGRADO:"No existen registros de estudiantes con las características ingresadas (Intente seleccionar otro periodo académico).",
        SIN_RESULTADOS:"No existen resultados asociados a los datos ingresados.",
        REGISTRAR_PAGO:"Error al registrar el pago",
        REGISTRAR_NOTA:"Error al registrar las notas",
        SIN_SOLICITUDES:"No existen solicitudes asociadas.",
        DOCENTE_DUPLICADO:"Por favor seleccione docentes diferentes en los campos de director y evaluador(es)",
        CARGA_SOLICITUDES:"Error al cargar las solicitudes",
        ENVIO_SOLICITUD:"Error al enviar la solicitud",
        NO_AREAS_CARGADAS:"Error al intentar cargar las áreas de conocimiento",
        NO_NUCLEOS_CARGADOS:"Error al intentar cargar los núcles básicos",
        CARGAR_CARRERAS:"Ocurrio un error al cargar las carreras asociadas al coordinador, por favor verifique su conexión e intente de nuevo.",
        CARGAR_FECHAS_MODALIDAD_POSGRADO:"Ocurrio un error al cargar las fechas asociadas a los procesos de la modalidad de materias de posgrado, por favor verifique su conexión e intente de nuevo.",
        SIN_FECHAS_MODALIDAD_POSGRADO:"Actualmenten no hay fechas para los procesos de la modadlidad de materias de posgrado asociadas al periodo academico.",
        SIN_CARRERAS_POSGRADO:"Señor Coordinador, no tiene asignadas carreras con nivel de POSGRADO",
        NO_EN_FECHAS_INSCRIPCION_POSGRADO:"El proceso de inscripción de materias para cursar la modalidad de materias de posgrado no se encuentra vigente.",
        NO_EN_FECHAS_PUBLICACION_POSGRADO:"El proceso de publicación de materias para cursar la modalidad de materias de posgrado no se encuentra vigente.",
        NO_EN_FECHAS_APROBACION_POSGRADO:"El proceso de aprobación de solicitudes de materias de posgrado no se encuentra vigente, tenga en cuenta que las fechas de aprobación van desde {{inicio}} hasta {{fin}}.",
        CARGANDO_SOLICITUDES_PARA_FORMALIZAR: "Ocurrió un error al cargar las solicitudes para formalizar. Comuníquese con el proyecto curricular.",
        FUERA_PERIODO_FORMALIZACION: "Este periodo no corresponde al periodo de formalización de solicitudes",
        FORMALIZAR_SOLICITUD: "Error al formalizar la solicitud",
        SIN_INFO_SOLICITUDES_APROBADAS: "Información insuficiente para listar las solicitudes aprobadas al posgrado",
        CARGANDO_SOLICITUDES_APROBADAS: "Error durante la consulta de las solicitudes aprobadas. Comuníquese con el administrador.",
        SIN_PERIODO: "No hay información asociada al periodo académico actualmente.",
        CARGANDO_PERIODO: "Ocurrió un error al intentar consultar el periodo académico correspondiente. Comuníquese con el administrador.",
        SIN_RELACION_SESIONES: "No hay información asociada a las sesiones de actividad consultadas.",
        CARGANDO_RELACION_SESIONES: "Ocurrió un error al intentar consultar las sesiones de actividad. Comuníquese con el administrador.",
        NO_PERIODO_FORMALIZACION: "Este periodo no corresponde a las fechas de formalización. Verifique que se encuentra en las fechas de formalización indicadas.",
        SIN_SOLICITUDES_PARA_FORMALIZAR: "No existen solicitudes para formalizar actualmente.",
        SIN_INFO_ACADEMICA: "Error al cargar información académica.",
        SIN_DETALLE_SOLICITUD: "No hay información asociada al detalle de las solicitudes consultadas.",
        CARGANDO_DETALLE_SOLICITUD: "Ocurrió un error al intentar consultar el detalle de las solicitudes aprobadas. Comuníquese con el administrador.",
        SIN_USUARIO_SOLICITUD: "No hay información asociada al usuario de las solicitudes consultadas.",
        CARGANDO_USUARIO_SOLICITUD: "Ocurrió un error al intentar consultar el detalle de las solicitudes aprobadas. Comuníquese con el administrador.",
        SIN_RESPUESTA_SOLICITUD: "No hay información asociada a la respuesta de las solicitudes consultadas.",
        CARGANDO_RESPUESTA_SOLICITUD: "Ocurrió un error al intentar consultar la respuesta de las solicitudes aprobadas. Comuníquese con el administrador.",
        SIN_INFO_ESTUDIANTE: "No hay información asociada a los estudiantes necesarios para la consulta.",
        CARGANDO_INFO_ESTUDIANTE: "Ocurrió un error al intentar consultar la información académica de los estudiante asociados. Comuníquese con el administrador.",
        REGISTRANDO_MODALIDAD: "Error al registrar la modalidad seleccionada",
        INDEFINIDA_INFO_ACADEMICA: "No hay información académica definida para esta operación.",
        SIN_ESPACIOS_ACADEMICOS_INSCRITOS: "No hay información asociada a los espacios académicos inscritos de los trabajos de grado consultados.",
        CARGANDO_ESPACIOS_ACADEMICOS_INSCRITOS: "Ocurrió un error al intentar consultar los espacios académicos inscritos de los trabajos de grado consultados. Comuníquese con el administrador.",
        SIN_ESTUDIANTE_TRABAJO_GRADO: "No hay información asociada a los estudiantes de los trabajos de grado consultados.",
        CARGANDO_ESTUDIANTE_TRABAJO_GRADO: "Ocurrió un error al intentar consultar los estudiantes de los trabajos de grado consultados. Comuníquese con el administrador.",
        SIN_TRABAJO_GRADO: "No hay información asociada a los trabajos de grado consultados.",
        CARGANDO_TRABAJO_GRADO: "Ocurrió un error al intentar consultar los trabajos de grado consultados. Comuníquese con el administrador.",
        REGISTRANDO_NOTA: "Error al registrar las calificaciones ingresadas",
        NOTA_INVALIDA: "Las calificaciones ingresadas son inválidas. Por favor verificar los campos.",
        CARGAR_CUPOS:"Ocurrio un error al cargar el número de cupos disponibles, por favor verifique su conexión e intente de nuevo",
        NUMERO_ADMITIDOS:"El numero de admitidos es mayor al número de cupos disponibles ({{cuposDisponibles}})",
        CARGAR_DATOS_SOLICITUDES:"Ocurrio un error al cargar los datos de las solicitudes, por favor verifique su conexión e intente de nuevo.",
        CARGAR_DATOS_ESTUDIANTES:"Ocurrio un error al cargar la información de los estudiantes, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_SOLICITANTES:"Ocurrio un error al cargar los solicitantes, por favor verifique su conexión e intente de nuevo.",
        VARLIDAR_REQUISITOS:"Ocurrio un error al validar los requisitos de la solicitud, por favor verifique su conexión e intente de nuevo.",
        CARGAR_RESPUESTA_SOLICITUD:"Ocurrio un error al cargar las respuestas de las solicitudes, por favor verifique su conexión e intente de nuevo.",
        CARGAR_AREAS:"Ocurrio un error al cargar las áreas de conocimiento, por favor verifique su conexión e intente de nuevo.",
        CARGAR_DATOS_ESTUDIANTE:"Ocurrio un error al cargar la información del estudiante, por favor verifique su conexión, e intente de nuevo.",
        ESTUDIANTE_NO_ENCONTRADO:"El estudiante no se encuentra",
        CARGAR_DATOS_TRABAJOS:"Ocurrio un error al cargar los datos de los trabajos de grado, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_TIPOS_SOLICITUD:"Ocurrio un error al cargar los tipos de solicitud, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_DETALLES_SOLICITUD:"Ocurrio un error al cargar los detalles de la solicitud, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_OPCIONES_DETALLES_SOLICITUD:"Ocurrio un error al cargar las opciones de los detalles, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_ASIGNATURAS_SOLICITUD:"Ocurrio un error al cargar las asignaturas disponibles, por favor verifique su conexión, e intente de nuevo.",
        CARGAR_DATOS_SOLICITUD:"Ocurrio un error al cargar los datos de las solicitud, por favor verifique su conexión e intente de nuevo.",
        SOLICITUD_NO_ENCONTRADA:"El identificador de la solicitud no ha sido encontrado",
        CARGAR_EVALUADORES:"Ocurrio un error al cargar los docentes evaluadores, por favor verifique su conexión e intente de nuevo.",
        CARGAR_VINCULADOS_TRABAJO_GRADO:"Ocurrio un error al cargar los docentes vinculados al trabajo de grado, por favor verifique su conexión e intente de nuevo.",
        CARGAR_DOCENTES:"Ocurrio un error al cargar los docentes disponibles, por favor verifique su conexión e intente de nuevo.",
        NO_HAY_PERMISO:"Lo sentimos, no cuenta con los permisos necesarios para acceder a esta página.",
    },
    VERIFICAR_DOCUMENTO:"Ocurrio un error al intentar cargar un documento. Verifique su conexión y el tipo de documento ('.pdf') y el tamaño.",
    BTN: {
        GUARDAR_ESPACIOS_ACADEMICOS: "Guardar Espacios Académicos",
        CAMBIAR_ESPACIOS_ACADEMICOS: "Cambiar Espacios Académicos",
        VER_DETALLES: "Ver Detalles",
        RESPONDER_SOLICITUD:"Responder solicitud",
        REGISTRAR_TRABAJO_GRADO: "Registrar trabajo de grado",
        REGISTRAR_NOTA: "Registrar calificaciones ingresadas",
    },
    ENVIAR_SOLICITUD:"Enviar Solicitud",
    INGRESAR_PROPUESTA:"Ingrese el nombre de la propuesta",
    SELECCIONE_EMPRESA:"Seleccione el nombre de la empresa",
    CARTA_DIRIGIDA:"Ingrese el nombre de la persona a la cual va dirigida la carta",
    CARGO_DIRIGIDO:"Ingrese el cargo de la persona a la cual se dirige la carta",
    INGRESAR_RESUMEN_PROPUESTA:"Escriba un resumen de su propuesta",
    CARGUE_PROPUESTA:"Cargue su propuesta",
    DOCENTE_AVALA_PROPUESTA:"Seleccione el docente que avala la propuesta",
    ESPACIOS_ACADEMICOS:"Espacios académicos",
    CARGUE_CERTIFICACION_ARL:"Cargue la certificación de afiliación a la ARL",
    ESPACIOS_ACADEMICOS_MISMO_PERIODO:"¿Desea la inscripción de los espacios académicos de Trabajo de Grado I y Trabajo de Grado II en el mismo periodo académico?",
    JUSTIFICACION_SOLICITUD:"Escriba la causa con la que justifica la solicitud",
    DIRECTOR_ACTUAL:"Nombre del director actual",
    DIRECTOR_NUEVO:"Seleccione el docente que solicita como nuevo director",
    EVALUADOR_ACTUAL:"Seleccione el nombre del evaluador actual",
    EVALUADOR_NUEVO:"Seleccione el docente que sugiere como nuevo evaluador",
    HOJA_VIDA_DIRECTOR_EXTERNO_NUEVO:"Cargue la hoja de vida del nuevo director externo",
    SELECCIONE_TIPO_PRORROGA:"Seleccione el tipo de prórroga que va a solicitar",
    SELECCIONE_ESPACIOS_ACADEMICOS:"Seleccione los espacios academicos que desea solicitar",
    CANCELAR_ESPACIOS_ACADEMICOS:"Seleccione el espacio academico que desea cancelar",
    SELECCIONE_ESPACIO_SOLICITADO:"Seleccione el espacio academico que solicita",
    NOMBRE_ANTERIOR_PROPUESTA:"Nombre actual de la propuesta",
    ESCRIBA_NOMBRE_NUEVO_PROPUESTA:"Escriba el nuevo nombre de la propuesta",
    ANTERIOR_RESUMEN_PROPUESTA: "Resumen actual de la propuesta",
    ESCRIBA_RESUMEN_NUEVO_PROPUESTA:"Escriba el nuevo resumen de su propuesta",
    ANTERIOR_PROPUESTA:"Propuesta actual",
    CARGUE_NUEVA_PROPUESTA:"Cargue la nueva propuesta",
    ANTERIORES_AREAS_CONOCIMIENTO:"Areas de conocimiento actuales",
    SELECCIONE_NUEVAS_AREAS_CONOCIMIENTO:"Seleccione las nuevas áreas de conocimiento que abarca su proyecto",
    CARGUE_PLAN_INVESTIGACION:"Cargue el Plan de actividades de investigación",
    SELECCIONE_ESTRUCTURA_INVESTIGACION_AVALA:"Seleccione  la Estructura de investigación que avala la propuesta",
    SELECCIONE_DOCENTE_DESIGNADO_INVESTIGACION:"Seleccione el Docente director designado por la estructura de investigación",
    CARGUE_PLAN_NEGOCIOS:"Cargue el plan o el modelo de negocios",
    ANTERIOR_DIRECTOR_EXTERNO:"Director externo actual",
    ESCRIBA_DIRECTOR_EXTERNO_NUEVO:"Escriba el nombre del nuevo director externo",
    PLAN_INVESTIGACION_ANTERIOR:"Plan de actividades de investigación actual",
    CARGUE_PLAN_INVESTIGACION_NUEVO:"Cargue Plan de actividades de investigación nuevo",
    CREACION_INDIVIDUAL_COLECTIVA:"Seleccione si su creación es individual o colectiva",
    ANTERIOR_PLAN_NEGOCIOS:"Plan o modelo de negocios actual",
    CARGUE_NUEVO_PLAN_NEGOCIOS:"Cargue el Plan o modelo de negocios nuevo",
    SELECCIONE_ESTUDIANTES_PROYECTO:"Seleccione los estudiantes que pertenecen al proyecto",
    SOLICITUD_SIN_FORMULARIO:"Esta solicitud no requiere diligenciar ningún formulario. ¿Está seguro de querer enviarla?",
    NUMERO_RADICADO : "Número de radicado",
    TIPO_SOLICITUD : "Tipo de solicitud",
    ESTADO_SOLICITUD : "Estado de la solicitud",
    DETALLE : "Detalle",
    ESTUDIANTE_SIN_SOLICITUD : "El estudiante actualmente no ha realizado ninguna solicitud.",
    DIRIGIJASE_SOLICITUD :"Si desea realizar una nueva solicitud dirijase al modulo",
    COORDINADOR_SIN_SOLICITUD : "Señor coordinador actualmente usted no tiene solicitudes por revisar.",
    COORDINADOR_SIN_SOLICITUD_EN_CARRERA : "Señor coordinador actualmente usted no tiene solicitudes por revisar en esta carrera, por favor seleccione otra.",    
    DETALLES_SOLICITUD: "Detalles de la solicitud",
    INFORMACION_SOLICITUD: "Información de la solicitud",
    INFORMACION_ESTUDIANTE: "Información del estudiante",
    SOLICITANTE: "Solicitante",
    SOLICITANTES: "Solicitantes",
    CALIFICACION: "Calificación",
    LOADING:{
      CARGANDO_ESTUDIANTE:"Cargando datos del estudiante",
      ENVIANDO_FORLMULARIO:"Enviando formulario",
      CARGANDO_DETALLES:"Cargando detalles del formulario",
      CARGANDO_SOLICITUDES:"Cargando solicitudes",
      CARGANDO_DOCUMENTO:"Cargando documento",
      CARGANDO_DETALLES_SOLICITUD:"Cargando detalles de la solicitud",
      CARGANDO_ASIGNATURAS:"Cargando espacios académicos",
      CARGANDO_PENSUMS:"Cargando pensums",
      CARGANDO_AREAS:"Cargando áreas de SNIES",
      REGISTRANDO_AREA:"Registrando Área",
      CARGANDO_INFO_ACADEMICA: "Cargando información académica",
      CARGANDO_PARAMETROS:"Cargando parámetros",
      CARGANDO_SOLICITUDES_APROBADAS: "Cargando solicitudes aprobadas",
      CARGANDO_TRANSACCION_REGISTRO: "Cargando transacción de registro",
      CARGANDO_TRABAJOS_DE_GRADO: "Cargando trabajos de grado en modalidad de espacios académicos de posgrado",
      REGISTRANDO_RESPUESTAS:"Registrando respuestas de las solicitudes del proceso de admisión",
    },
    SELECT:{
      SELECCIONE:"Seleccione una opción",
      DOCENTE_CAMBIO: "Seleccione el docente para realizar el cambio",
      DOCENTE_DIRECTOR: "Seleccione el docente director del proyecto",
      DOCENTE_REVISOR: "Seleccione el docente revisor del proyecto",
      DOCENTE_REVISOR_FILTRO: "Escriba al menos 2 letras del nombre del docente revisor del proyecto",
      DOCENTE_DIRECTOR_FILTRO: "Escriba al menos 2 letras del nombre del docente director del proyecto",
      SIN_CARRERA:"No se ha seleccionado ninguna carrera",
      TIPO_DISTINCION:"Seleccione el tipo de distinción",
      TRABAJO_GRADO_EVALUAR:"Seleccione el trabajo de grado que desea evaluar",
      EVALUADOR_NUMERO:"Seleccione el evaluador numero {{numero}}",
      AREA_SNIES:"Seleccione el área de SNIES",
      NUCLEO_SNIES:"Seleccione el núcleo básico",
    },
    DOCUMENTO:{
        CARGAR_DOCUMENTO:"Cargar documento",
        INGRESE_NOMBRE:"Ingrese el nombre del documento",
        INGRESE_DESCRIPCION:"Ingrese la descripción del documento",
        SELECCIONE_DOCUMENTO:"Seleccione el documento",
        SIN_DOCUMENTO:"No hay ningún documento seleccionado",
        SELECCIONAR_DOCUMENTO:"Seleccionar documento",
        VER_DOCUMENTO:"Ver documento",
        CARGADO:"Documento Cargado",
        INGRESE_CONSECUTIVO: "Ingrese el consecutivo del documento",
    },
    SWITCH:{
        SI:"SI",
        NO:"NO",
    },
    CODIGO_MATERIA:"Codigo asignatura",
    SIN_CARRERAS_SOLICITUDES:"Actualmente no hay carreras disponibles para su elección",
    APROBAR_SOLICITUD:"Aprobar solicitud",
    RECHAZAR_SOLICITUD:"Rechazar solicitud",
    FORMULARIO_APROBACION:"Formulario de aprobación",
    JUSTIFICACION_RESPUESTA_SOLICITUD:"Escriba la justificación de la respuesta",
    ACTA_RESPUESTA_SOLICITUD:"Seleccione el acta de la respuesta dada por el consejo de carrera",
    RESPUESTA_SOLICITUD:"Respuesta a la solicitud",
    SOLICITUD_APROBADA:"La respuesta a la solicitud ha sido registrada exitosamente",
    SOLICITAR_DISTINCION:"Desea solicitar una distinción para este trabajo de grado",
    JUSTIFICACION_RESPUESTA:"Justificación del estado",
    AUTORIZACION_DERECHOS_AUTOR:"Yo <u> {{nombre}}</u> con código <u>{{codigo}}</u>, manifiesto mi voluntad de ceder los derechos de autor del trabajo de grado <u> {{tg}} </u> a los demás estudiantes relacionados.",
    SELECCIONE_ACTA:"Seleccione el acta mediante la cual se da respuesta a la solicitud",
    SOLICITUD_CON_RESPUESTA:"La solicitud ya fue atendida.",
    SOLICITUD_SIN_RESPUESTA:"La solicitud no ha sido atendida",
    RESULTADO_SOLICITUD:"Resultado de la solicitud",
    SOLICITUD_RECHAZADA:"La solicitud fue rechazada",
    SOLICITUD_ES_APROBADA:"La solicitud fue aprobada",
    SOLICITUD_OPCIONADA_SEGUNDA_CONVOCATORIA:"La solicitud esta opcionada para el segundo proceso de admisión.",
    SOLICITUD_RECHAZADA_CUPOS_INSUFICIENTES:"La solicitud fue rechazada por disponibilidad de cupos en el posgrado.",
    SOLICITUD_APROBADA_EXENTA:"La solicitud fue aprobada exenta de pago, el estudiante puede formalizarla.",
    INFORMACION_PRORROGA:"Información importante sobre la prórroga",
    MENSAJE_PRORROGA:"Señor estudiante, se le informa que según lo estipulado en el Acuerdo 038 de Julio de 2015  expedido por el consejo académico de la Universidad Distrital Francisco José de Caldas, usted solo tiene derecho a una prórroga, es decir, una vez usted realice esta solicitud sin importar su naturaleza (prórroga para socializar o radicar) y está sea aprobada no podrá volver a solicitarla.",
    APROBADO : {
        CURSAR_MODALIDAD: "El estudiante puede cursar la modalidad de {{modalidad}}",
        CANCELAR_MODALIDAD: "El estudiante ya no cursa la modalidad de {{modalidad}}",
        CAMBIAR_NOMBRE:"Se cambio el nombre del trabajo de grado '{{anterior}}' por '{{nuevo}}'",
        DIRECTOR_INTERNO:"Se cambio el director interno {{anterior}} por {{nuevo}}",
        EVALUADOR:"Se cambio el evaluador {{anterior}} por {{nuevo}}",
        PRORROGA:"Se concede la prorroga solicitada, por lo tanto el estudiante no podrá volver a solicitar una",
        CAMBIAR_MATERIA:"Se cambia la materia {{anterior}} por {{nuevo}}",
    },
    AREAS:{
        DATOS_AREA:"Datos para registrar área",
        INGRESE_NOMBRE_AREA:"Ingrese el nombre de la nueva área",
        INGRESE_DESCRIPCION_AREA:"Ingrese la descripción del área",
        REGISTRAR_AREA:"Registrar área",
        AREA_REGISTRADA:"El área  de conocimiento se registro correctamente.",
        ERROR_REGISTRAR_AREA:"No se pudo registrar el area.",
        AREA_EXISTENTE:"El área de conocimiento ya está registrada",
    },
    REGISTRO_EXITOSO:"Registro exitoso",
    DOCUMENTO_RESPUESTA_SOLICITUD:"Documento con el que se respondió la solicitud",
    EVALUADOR:"Evaluador(es)",
    DIRECTOR_INTERNO:"Director interno",
    ESPACIOS_ACADEMICOS_GUARDADOS:"Espacios Académicos Guardados",
    MENSAJE_ESPACIOS_ACADEMICOS_GUARDADOS:"Los espacios académicos seleccionados podrán ser elegidos por los estudiantes para optar por la modalidad de trabajo de grado",
    MAS_ESPACIOS_ACADEMICOS:"Seleccione más espacios académicos",
    CREDITOS_ESPACIOS_ACADEMICOS_INSUFICIENTES:"La cantidad de créditos de los espacios académicos seleccionados debe ser igual o superior a {{creditos}} créditos",
    ADMINISTRAR_AREAS:"Administrar áreas de conocimiento",
    SIN_AREAS:"Actualmente no hay áreas de conocimiento registradas para esta área del SNIES",
    DESCRIPCION:"Descripción",
    NO_SOLICITUDES_POSGRADO:"No existen solicitudes en la modalidad de espacios académicos de posgrado para la carrera seleccionada",
    SELECCIONAR_PERIODO: "Seleccione el periodo académico",
    PASANTIA:{
      SOLICITAR_CARTA:"Solicitar carta de presentación",
      INGRESE_NOMBRE_EMPRESA:"Ingrese el nombre de la empressa",
      INGRESE_NOMBRE_DIRIGIDO:"Ingrese el nombre del destinatario de la carta",
      INGRESE_CARGO_DIRIGIDO:"Ingrese el cargo del destinatario de la carta",
      RECLAMAR_CARTA:"Señor estudiante tenga en cuenta que una vez su solicitud de carta de presentación sea aprobada debera acercarse a recogerla en la oficina de pasantias",
      SEGURO_INFORMACION_CARTA:"Señor estudiante, ¿Está seguro solicitar una carta dirigida al Señor(a) {{nombre}} quien labora como {{cargo}} en la empresa {{empresa}}?, por favor verifique todos los datos.",
    },
    ACEPTAR:"Aceptar",
    CANCELAR:"Cancelar",
    FECHAS_PROCESO_MATERIAS_POSGRADO:"Fechas del proceso de la modalidad de materias de posgrado",
    FECHA_INICIO:"Fecha de inicio",
    FECHA_FIN:"Fecha fin",
    FORMALIZAR_SOLICITUD: {
        TITULO: "Formalización de solicitudes",
        CONFIRMACION: "Confirmación para formalizar la solicitud seleccionada",
        ACCION: "Formalizar",
        MENSAJE_CONFIRMACION: "¿Está seguro de formalizar la solicitud {{idSolicitud}}, en estado {{nombreEstado}}, para cursar espacios académicos en el posgrado {{nombrePosgrado}}?",
        AVISO: "Formalización de la solicitud",
        SOLICITUD_FORMALIZADA: "La solicitud fue formalizada con éxito",
        REVISAR_FECHAS_FORMALIZACION: "Revise los periodos de formalización, o comuníquese con el proyecto curricular",
        FECHAS_PARA_FORMALIZACION: "Fechas válidas para realizar el proceso de formalización",
        FORMALIZACION_NO_HABILITADA: "El estado de esta solicitud no la habilita para ser formalizada",
    },
    LISTAR_APROBADOS: {
        TITULO: "Listado de estudiantes admitidos al posgrado",
        REGISTRAR: "Registrar",
        DESCRIPCION: "Descripción de la solicitud seleccionada",
        REGISTRAR_ESTUDIANTE: "¿Está seguro de registrar al estudiante {{nombre}}, con código estudiantil {{codigo}} en estado {{estado}}, para la modalidad de materias de posgrado?",
        AVISO: "Registro de la solicitud aprobada",
        ESTUDIANTE_REGISTRADO: "La modalidad para espacios académicos de posgrado ha sido registrada con éxito",
    },
    REGISTRAR_NOTA: {
        TITULO: "Registro de calificaciones en espacios académicos de posgrado",
        CONFIRMACION: "Registrar calificaciones",
        MENSAJE_CONFIRMACION: "¿Está seguro de registrar las calificaciones ingresadas para los espacios académicos del estudiante {{nombre}}, con código estudiantil {{codigo}}?",
        AVISO: "Registro de calificaciones",
        NOTA_REGISTRADA: "Las calificaciones ingresadas han sido registradas con éxito.",
        DESCRIPCION: "Descripción del trabajo de grado seleccionado",
        INSTRUCCIONES: "Ingrese las calificaciones obtenidas por el estudiante haciendo click sobre la celda correspondiente. Tenga en cuenta que las calificaciones válidas van desde 0.0 hasta 5.0, y se tomarán dos (2) decimales de precisión para el registro."
    },
    PERIODO_ACADEMICO:"Período académico",
    SOLICITUD_NO_PUEDE_APROBARSE:"La solicitud no puede ser aprobada",
    MATERIAS_POSGRADO:{
        CONFIRMACION_ADMITIR:"Confirmación de admitidos",
        CONFIRMAR:"Al presionar aceptar confirma que desea ejecutar el proceso de admisión con los estudiantes seleccionados, esta acción no puede deshacerse.",
        ADMITIDOS:"Se admitirán los siguientes estudiantes:",
        OPCIONADOS:"Los siguientes estudiantes serán opcionados para la segunda convocatoria:",
        NO_ADMITIDOS:"Los siguientes estudiantes no se admitirán por falta de cupos:",
        PROCESO_ADMISION_COMPLETO:"Proceso de admisión completado",
        RESPUESTAS_SOLICITUD:"Se han registrado los datos del proceso de admisión exitosamente",
    },
    NO_OPCIONES_DISPONIBLES:"No hay opciones dispobiles",
    ACCESO_NEGADO:"Acceso negado",
    ACCION_NO_DISPONIBLE:"Acción no disponible",
};
var text_en = {
    TITULO: "GENERATOR-OAS",
    MENSAJE_INICIAL: "Now get to start to develop",
    LISTADO_SOLICITUD: "List of Requests",
    MODALIDAD: "Modality",
    TITULO_PROPUESTA: "Title of proposal",
    VER_DOCUMENTO: "Show document",
    ESTADO_DOCUMENTO: "Document Status",
    RESUMEN: "Abstract",
    OPCIONES: "Options",
    SOLICITUD: "Request",
    ASIGNAR_DOCENTE: "Assign Teacher",
    FECHA: "Date",
    HORA: "Time",
    SELECCIONE_FORMATO: "Select the format",
    AREAS_CONOCIMIENTO: "Knowledge Area",
    LISTAR_SOLICITUDES: "List of request",
    ANO: "Year",
    PERIODO:"Period",
    CARRERA: "Carrer",
    POSGRADO: "Postgraduate",
    CODIGO_POSGRADO: "Postgraduate code",
    CODIGO_ESP_ACADEMICO: "Subject's code",
    CODIGO_PENSUM_POSGRADO: "Code of the list of subjects published for the postgraduate",
    PENSUM: "List of subjects",
    EVALUAR_PROYECTO: "Evaluate graduation project",
    SELECCIONAR_CARRERA: "Select a carrer",
    SELECCIONAR_PENSUM: "*Select a list of subjects",
    CODIGO: "Code",
    NOMBRE: "Name",
    NOMBRE_ESP_ACADEMICO: "Subject's name",
    ESP_ACADEMICOS: "Subjects",
    MODALIDAD_ESP_POS: "Modality: Postgraduate subjects",
    MODALIDAD_ESP_PROFUNDIZACION: "Modality: Deepening subjects",
    ADMITIDOS_POR_RENDIMIENTO: "Admited by academic performance:",
    ADMITIDOS_POR_ECONOMIA: "Admited by payment:",
    FECHA_ACTUAL: "Current date:",
    FECHA_INICIO_UNO: "Start date:",
    FECHA_INICIO_DOS: "Second start date:",
    FECHA_FIN: "Ending date:",
    SELECCION_DE_ADMITIDOS: "Selection of admitted students",
    ADMITIDOS_POR_EXCELENCIA_A: "Admitted by academic performance and no payment (Max",
    ADMITIDOS_POR_COND_EC: "Admitted by academic performance and payment (Max",
    REQUERIDO: "It's required",
    PUBLICACION_DE_ESPACIOS: "Announcement of subjects list.",
    RESPUESTA: "Answer:",
    DENEGADO: "The student doesn't meet the requirements in order aply to this modality",
    REGISTRAR_PROPUESTA: "Register proposal.",
    ESTADO: "Status:",
    ESTADO_SIN_DOSPUNTOS: "Status",
    PORCENTAJE_CURSADO: "Percentage completed",
    PROMEDIO: "Average",
    RENDIMIENTO: "Academic performance",
    NIVEL_ESTUDIOS: "Level of study:",
    TIPO_CARRERA: "Carrer type",
    REGISTRAR_TRABAJO_DE_GRADO: "Register graduation work.",
    EDICION_FORMATO_EVALUACION: "Edition of test formats",
    SELECCIONAR_FORMATO: "Select format:",
    EDICION_GENERAL: "General edition",
    TITULO_FORMATO: "Tittle of the format:",
    INTRODUCCION: "Introduction:",
    EDICION_PREGUNTAS: "Edition of questions",
    ENUNCIADO: "Statement:",
    PESO: "Value:",
    TIPO: "Type:",
    NUEVA_EVALUACION: "New test",
    BUSCAR_FORMATOS: "Search formats",
    NOMBRE_FORMATO: "Format name",
    INTRODUCCION_FORMATO: "Format introduction",
    ANADIR_PREGUNTA: "Add question",
    ANADIR_OPCION: "Add option",
    VISTA_PREVIA: "Preview",
    ASIGNAR_FORMATO_A_PC: "Asign format to a curricular project:",
    ASOCIAR_FORMATO_A_PC: "Asociate format to a curricular project:",
    SELECCIONAR_PC: "Select a curricular project",
    CREACION_EVALUACION: "Creation of the test",
    REVISION_DOCUMENTOS: "Documents review",
    DOCUMENTO: "Document",
    REVISIONES: "Reviews",
    LA_REVISION: "The review ",
    LA_REVISION_SE_ENCUENTRA: " is in process",
    SUBIR_DOCUMENTO: "Upload document",
    PUBLICAR_ASIGNATURA: "Announce subject",
    SOLICITUDES_DEL_ESTUDIANTE: "Student solicitudes",
    NINGUNA_SOLICITUD_REALIZADA: "You have not done any request",
    SOLICITUD_NUM: "Request N° ",
    FORMALIZACION: "Formalization: ",
    CREDITOS: "Credits ",
    SEMESTRE: "Semester ",
    ESTUDIANTE_ACTUAL: "Current student",
    TITULO_TG: "Graduation work tittle",
    ASIGNAR_AREA: "Asign area",
    DE_ACUERDO_A_SU_PROPUESTA: "According to your proposal, select the areas, then attach the doc file",
    ESTUDIANTE: "Student",
    NOMBRE_PROPUESTA: "Proposal name: ",
    DE_ACUERDO_A_SU_PROPUEST: "According to your proposal, select the areas",
    SELECCIONE_LAS_OPCIONES: "Select the options to link a teacher",
    FILTRANDO_POR: "Filtering by: ",
    VINCULAR_DOCENTE: "Link teacher",
    NOMBRE_DEL_DOCUMENTO: "Document name",
    SELECCIONE_EL_DOCUMENTO: "Choose the document",
    CARGAR_ARCHIVO: "Load file",
    ARRASTRE_O_CLICK: "Click to load the file",
    GUARDAR_REGISTRO: "Save",
    CANCELAR: "Cancel",
    BORRAR: "Delete",
    CALIFICACION_FINAL_PG: "Final qualification of the Graduation project ",
    ENVIAR_EVALUACION: "Send Qualification",
    FECHA_REVISION: "Review date: ",
    REVISION: "Review ",
    INGRESE_NUEVA_AREA: "Enter a new area",
    NOMBRE_MUY_CORTO: "That's a very short name!",
    NOMBRE_MUY_EXTENSO: "That's a very long name!",
    DE_ACUERDO_A_SU_PERFIL: "According to your profile, choose the areas of knowledge: ",
    EL_AREA_NO_EXISTE: "The area of knowledge doesn't exist",
    NO_EXISTEN_AREAS: "There aren't areas of knoeledge",
    AREAS_DOCENTE: "Areas of knowledge for the teacher",
    DOCENTE_ACTUAL: "Current teacher: ",
    GUARDAR: "Save",
    OPCION_BOTON: " + Option",
    PREGUNTA_BOTON: " + Question",
    ASIGNAR_BOTON: " Asign",
    SEL_FECHA: "Select a date",
    ENVIAR_EVALUACION_BOTON: "Send qualification",
    SOLICITAR_REVISION: "Request review",
    SELECCIONAR: "Select",
    NUEVA_SOLICITUD: "Create new request",
    GESTION_SOLICITUD: "Request management module. ",
    SELECCIONAR_MODALIDAD:"Select modality",
    SELECCIONAR_SOLICITUD:"Select request type",
    FORMULARIO_SOLICITUD:"Request form",
    SELECCIONE_AREAS_CONOCIMIENTO:"Select the knowledge areas of your project",
    NOMBRE_CORTO:"Very short name",
    NOMBRE_LARGO:"Very long name",
    NUEVA_AREA:"Enter new area",
    TRABAJO_GRADO:"Degree assignment",
    AGREGAR_ESTUDIANTES:"Add students to the request",
    INGRESE_CODIGO:"Enter the code of the other students of the project",
    ESTUDIANTE_EN_LISTA:"Error: The student is already in the requested list.",
    ESTUDIANTE_NO_VALIDO:"Error: The code is not valid.",
    ESTUDIANTE_NO_REQUISITOS:"Error: The currently requested student does not meet the requirements to complete a grade level assignment.",
    ESTUDIANTE_TRABAJO_GRADO:"Error: The currently requested student is performing a degree assignment.",
    FALTAN_DATOS_ESTUDIANTE:"Error: No student data was found.",
    CANTIDAD_EXCEDIDA:"Error: The number of students for the requested modality is exceeded.",
    SOLICITAR_ASIGNATURAS:"Request Subjects",
    ANIO:"Year",
    ERROR:"ERROR",
    NO_CARRERAS_POSGRADO:"You do not have assigned courses with a POSTGRADUATE level",
    NO_CARRERAS_PREGRADO:"You do not have assigned courses with a UNDERGRADUATE level",
    NO_PENSUMS:"The career does not have active pensums",
    NO_ASIGNATURAS:"There are no academic spaces belonging to the selected curriculum",
    NOMBRE_EMPRESA:"Enter the name of the company",
    REGISTRO_FORMULARIO:"Form Submit",
    REGISTRO_PAGO:"Payment submit",
    REGISTRO_NOTA:"Grades record",
    SOLICITUD_REGISTRADA:"The form was successfully registered",
    ERROR_CARGAR_SOLICITUDES:"There was an error loading the request.",
    ERROR_SOLICITUDES_1:"There was an error inserting the details of the request.",
    ERROR_SOLICITUDES_2:"There was an error inserting the users of the request",
    ERROR_SOLICITUDES_3:"There was an error inserting the answer of the request",
    ERROR_RTA_SOLICITUD_1: "There was an error to update the answer of the request.",
    ERROR_RTA_SOLICITUD_2: "There was an error inserting the answer of the request.",
    ERROR_RTA_SOLICITUD_3: "There was an error inserting the response act of the request.",
    ERROR_RTA_SOLICITUD_4: "There was an error inserting the graduation work.",
    ERROR_RTA_SOLICITUD_5: "There was an error inserting the link of the graduation work.",
    ERROR_RTA_SOLICITUD_6: "There was an error to update the link of the graduation work.",
    ERROR_RTA_SOLICITUD_7: "There was an error to update the student's status in the graduation work.",
    ERROR_RTA_SOLICITUD_8: "Error when canceling the graduation work.",
    ERROR_RTA_SOLICITUD_9: "There was an error inserting the stundent in the graduation work.",
    ERROR_RTA_SOLICITUD_10: "There was an error inserting the knowledge areas of the graduation work.",
    ERROR_RTA_SOLICITUD_11: "There was an error inserting the document of the graduation work.",
    ERROR_RTA_SOLICITUD_12: "There was an error inserting the written document to the proposal of the graduation work.",
    ERROR_RTA_SOLICITUD_13: "There was an error to update the graduation work.",
    ERROR: {
        SUBIR_DOCUMENTO:"Error attempting to load a document.",
        CARGAR_DOCUMENTO:"An error occurred loading the documents, please verify your connection and try again.",
        HAY_SOLICITUD_DISTINCION:"Currently there is already a request for outstanding distinction for this degree work.",
        HAY_SOLICITUD_PENDIENTE:"Currently the student already has a grade job request that is pending by response.",
        DOCENTE_DUPLICADO:"Please select different teachers in the fields of director and evaluator(s).",
        CARGA_SOLICITUDES:"Error loading requests.",
        NO_AREAS_CARGADAS:"Error trying to load knowledge areas.",
        NO_NUCLEOS_CARGADOS:"Error trying to load basic cores.",
        SIN_INFO_ACADEMICA:"Error during academic information load.",
        NO_EXISTE_ESTUDIANTE_POSGRADO:"There are no records of students with the requested characteristics (Try selecting another academic period).",
        SIN_RESULTADOS:"There are no results associated with the data requested.",
        REGISTRAR_PAGO:"Error registering the payment",
        REGISTRAR_NOTA:"Error registering the grades",
        SIN_SOLICITUDES:"There are not associated requests.",
        DOCENTE_DUPLICADO:"Please select different teachers in the fields of director and evaluator(s)",
        CARGA_SOLICITUDES:"Error loading requests",
        NO_AREAS_CARGADAS:"Error trying to load knowledge areas",
        NO_NUCLEOS_CARGADOS:"Error trying to load basic cores",
        NO_AREAS_CARGADAS:"Error trying to load knowledge areas",
        NO_NUCLEOS_CARGADOS:"Error trying to load basic numbers",
        CARGAR_CARRERAS:"An error occurred loading the races associated with the coordinator, please verify your connection and try again.",
        CARGAR_FECHAS_MODALIDAD_POSGRADO:"An error occurred loading the dates associated with the processes of the postgraduate course mode, please verify your connection and try again.",
        SIN_FECHAS_MODALIDAD_POSGRADO:"Currently there are no dates for the processes of the postgraduate subjects modality associated with the academic period.",
        SIN_CARRERAS_POSGRADO:"Mr. Coordinator, you have not assigned careers with a POSTGRADUATE level.",
        NO_EN_FECHAS_INSCRIPCION_POSGRADO:"The process of registration of subjects to course the postgraduate subjects modality is not in force.",
        NO_EN_FECHAS_PUBLICACION_POSGRADO:"The process of publication of subjects to course the postgraduate subjects modality is not in force.",
        CARGANDO_SOLICITUDES_PARA_FORMALIZAR: "There was an error loading the requests to formalize. Communicate with the curricular project.",
        FUERA_PERIODO_FORMALIZACION: "This period does not correspond to the period of requests formalization",
        SIN_INFO_SOLICITUDES_APROBADAS: "Insufficient information to list approved requests to the postgraduate",
        CARGANDO_SOLICITUDES_APROBADAS: "Error during the query of the approved requests. Contact the administrator.",
        SIN_PERIODO: "There is not currently information associated with the academic period.",
        CARGANDO_PERIODO: "An error occurred while trying to query the corresponding academic period. Contact the administrator.",
        SIN_RELACION_SESIONES: "There is no information associated with the queried activity sessions.",
        CARGANDO_RELACION_SESIONES: "An error occurred while trying to query the activity sessions. Contact the administrator.",
        NO_PERIODO_FORMALIZACION: "This period does not correspond to the formalization dates. Verify that you are in the indicated formalization dates.",
        SIN_SOLICITUDES_PARA_FORMALIZAR: "There are not currently requests to formalize.",
        FORMALIZAR_SOLICITUD: "Error formalizing the request",
        SIN_INFO_ACADEMICA: "Error during academic information load.",
        SIN_DETALLE_SOLICITUD: "There is no information associated with the detail of the queried requests.",
        CARGANDO_DETALLE_SOLICITUD: "An error occurred while trying to query the detail of the approved requests. Contact the administrator.",
        SIN_USUARIO_SOLICITUD: "There is no information associated with the user of the queried requests.",
        CARGANDO_USUARIO_SOLICITUD: "An error occurred while trying to query the user of the approved requests. Contact the administrator.",
        SIN_RESPUESTA_SOLICITUD: "There is no information associated with the response of the queried requests.",
        CARGANDO_RESPUESTA_SOLICITUD: "An error occurred while trying to query the response of the approved requests. Contact the administrator.",
        SIN_INFO_ESTUDIANTE: "There is no information associated with the students needed for the query.",
        CARGANDO_INFO_ESTUDIANTE: "An error occurred while trying to query the academic information of the associated students. Contact the administrator.",
        REGISTRANDO_MODALIDAD: "Error during register the selected modality",
        INDEFINIDA_INFO_ACADEMICA: "There is no academic information defined for this operation.",
        SIN_ESPACIOS_ACADEMICOS_INSCRITOS: "There is no information associated to the academic spaces enrolled of the degree works consulted.",
        CARGANDO_ESPACIOS_ACADEMICOS_INSCRITOS: "An error occurred when trying to query the academic spaces enrolled for the degree works consulted. Contact the administrator.",
        SIN_ESTUDIANTE_TRABAJO_GRADO: "There is no information associated to the students of the degree works consulted.",
        CARGANDO_ESTUDIANTE_TRABAJO_GRADO: "An error occurred when trying to query the students for the degree works consulted. Contact the administrator.",
        SIN_TRABAJO_GRADO: "There is no information associated to the degree works consulted.",
        CARGANDO_TRABAJO_GRADO: "An error occurred when trying to query the degree works consulted. Contact the administrator.",
        REGISTRANDO_NOTA: "Error during register the entered grades",
        NOTA_INVALIDA: "The grades entered are invalid. Please check the fields.",
        CARGAR_CUPOS:"There was an error lloading the number of avaliable quotas, please verify your connection and try again.",
        NUMERO_ADMITIDOS:"The number of admitted is greater than the number of available places ({{cuposDisponibles}})",
        CARGAR_DATOS_SOLICITUDES:"There was an error occurred loading the requests data, please check your connection and try again.",
        CARGAR_DATOS_ESTUDIANTES:"There was an error occurred loading the students information, please check your connection and try again.",
        CARGAR_SOLICITANTES:"There was an error occurred loading the requests, please check your connection and try again.",
        VARLIDAR_REQUISITOS:"There was an error occurred by validating the requirements of the application, please check your connection and try again.",
        CARGAR_RESPUESTA_SOLICITUD:"There was an error occurred loading the request's response, please check your connection and try again.",
        CARGAR_AREAS:"There was an error occurred loading the areas of knoeledge, please check your connection and try again.",
        CARGAR_DATOS_ESTUDIANTE:"There was an error occurred loading the student's information, please check your connection and try again.",
        ESTUDIANTE_NO_ENCONTRADO:"The student is not found",
        CARGAR_DATOS_TRABAJOS:"There was an error occurred loading the grade job data, please check your connection and try again.",
        CARGAR_TIPOS_SOLICITUD:"There was an error occurred loading the types of request, please check your connection and try again.",
        CARGAR_DETALLES_SOLICITUD:"There was an error occurred loading the request's details, please check your connection and try again.",
        CARGAR_OPCIONES_DETALLES_SOLICITUD:"There was an error occurred loading the options of the details of the request, please check your connection and try again.",
        CARGAR_ASIGNATURAS_SOLICITUD:"There was an error occurred loading the avaliable subjects, please check your connection and try again.",
        CARGAR_DATOS_SOLICITUD:"There was an error occurred loading the request data, please check your connection and try again.",
        SOLICITUD_NO_ENCONTRADA:"The identifier of the request has not been found.",
        CARGAR_EVALUADORES:"There was an error occurred loading the evaluators, please check your connection and try again.",
        CARGAR_VINCULADOS_TRABAJO_GRADO:"There was an error occurred loading the teachers related to degree work, please check your connection and try again.",
        CARGAR_DOCENTES:"There was an error occurred loading the avaliable teachers, please check your connection and try again.",
        NO_HAY_PERMISO:"Sorry, you do not have the necessary permissions to access to this page.",
    },
    VERIFICAR_DOCUMENTO:"An error occurred while trying to load a document. Check your connection and document type (.pdf) and the size. ",
    BTN: {
        GUARDAR_ESPACIOS_ACADEMICOS: "Save academic spaces",
        CAMBIAR_ESPACIOS_ACADEMICOS: "Change academic spaces",
        VER_DETALLES: "View details",
        RESPONDER_SOLICITUD:"Reply request",
        REGISTRAR_TRABAJO_GRADO: "Submit degree work",
        REGISTRAR_NOTA: "Submit entered grades",
    },
    ENVIAR_SOLICITUD:"Send Form",
    INGRESAR_PROPUESTA:"Enter the name of the proposal",
    SELECCIONE_EMPRESA:"Select the name of the company",
    CARTA_DIRIGIDA:"Enter the name of the person to whom the letter is addressed",
    CARGO_DIRIGIDO:"Enter the position of the person to whom the letter is addressed",
    INGRESAR_RESUMEN_PROPUESTA:"Write a summary of your proposal",
    CARGUE_PROPUESTA:"Upload your proposal",
    DOCENTE_AVALA_PROPUESTA:"Select the teacher who supports the proposal",
    ESPACIOS_ACADEMICOS:"Academic spaces",
    CARGUE_CERTIFICACION_ARL:"Upload the certification of the affiliation to the ARL",
    ESPACIOS_ACADEMICOS_MISMO_PERIODO:"Select if you want to register the two degree workspaces in the same period.",
    JUSTIFICACION_SOLICITUD:"Write the cause that justifies the request",
    DIRECTOR_ACTUAL:"Name of current director",
    DIRECTOR_NUEVO:"Select the teacher requestes as  new director",
    EVALUADOR_ACTUAL:"Select the name of the current evaluator",
    EVALUADOR_NUEVO:"Select the teacher that you suggest as the new evaluator",
    HOJA_VIDA_DIRECTOR_EXTERNO_NUEVO:"Upload the resume of the new external director",
    SELECCIONE_TIPO_PRORROGA:"Select the type of extension that you are requesting",
    SELECCIONE_ESPACIOS_ACADEMICOS:"Select the academic spaces that you want to request",
    CANCELAR_ESPACIOS_ACADEMICOS:"Select the academic space that you want to cancel",
    SELECCIONE_ESPACIO_SOLICITADO:"Select the academic space that you are requesting",
    NOMBRE_ANTERIOR_PROPUESTA:"Current name of proposal",
    ESCRIBA_NOMBRE_NUEVO_PROPUESTA:"Write the new name of the proposal",
    ANTERIOR_RESUMEN_PROPUESTA: "Current summayof the proposal",
    ESCRIBA_RESUMEN_NUEVO_PROPUESTA:"Write the new summary of your proposal",
    ANTERIOR_PROPUESTA:"Current proposal",
    CARGUE_NUEVA_PROPUESTA:"Upload the new proposal",
    ANTERIORES_AREAS_CONOCIMIENTO:"Current areas of knowledge",
    SELECCIONE_NUEVAS_AREAS_CONOCIMIENTO:"Select the new knowledge areas of your projec",
    CARGUE_PLAN_INVESTIGACION:"Upload the Plan of research activities",
    SELECCIONE_ESTRUCTURA_INVESTIGACION_AVALA:"Select the research structure that supports the proposal",
    SELECCIONE_DOCENTE_DESIGNADO_INVESTIGACION:"Select the director appointed by the research structure",
    CARGUE_PLAN_NEGOCIOS:"Upload plan or business model",
    ANTERIOR_DIRECTOR_EXTERNO:"Current external director",
    ESCRIBA_DIRECTOR_EXTERNO_NUEVO:"Enter the name of the new external director",
    PLAN_INVESTIGACION_ANTERIOR:"Current plan of researchs",
    CARGUE_PLAN_INVESTIGACION_NUEVO:"Upload New Research Activities Plan",
    CREACION_INDIVIDUAL_COLECTIVA:"Select if your creation is individual or collective",
    ANTERIOR_PLAN_NEGOCIOS:"Current Previous Business Plan or Model",
    CARGUE_NUEVO_PLAN_NEGOCIOS:"Upload the new business plan or model",
    SELECCIONE_ESTUDIANTES_PROYECTO:"Select the students that belong to the project",
    SOLICITUD_SIN_FORMULARIO:"This request does not require completing any form. Are you sure you want to send it?",
    NUMERO_RADICADO : "Roaming number",
    TIPO_SOLICITUD : "Type of request",
    ESTADO_SOLICITUD : "Request state",
    DETALLE : "Detail",
    ESTUDIANTE_SIN_SOLICITUD : "The student has not made any request.",
    DIRIGIJASE_SOLICITUD : "If you want to make a new request go to the module",
    COORDINADOR_SIN_SOLICITUD : "Dear Coordinator, you do not currently have any requests to review.",
    COORDINADOR_SIN_SOLICITUD_EN_CARRERA : "Mr. Coordinator currently you have no requests to review in this race, please select another.",    
    DETALLES_SOLICITUD: "Request's details",
    INFORMACION_SOLICITUD: "Request's information",
    INFORMACION_ESTUDIANTE: "Student's information",
    SOLICITANTE: "Applicant",
    SOLICITANTES: "Applicants",
    CALIFICACION: "Grade",
    LOADING:{
      CARGANDO_ESTUDIANTE:"Loading student data",
      ENVIANDO_FORLMULARIO:"Sending form",
      CARGANDO_DETALLES:"Loading form details",
      CARGANDO_SOLICITUDES:"Loading requests",
      CARGANDO_DOCUMENTO:"Loading document",
      CARGANDO_DETALLES_SOLICITUD:"Loading request details",
      CARGANDO_ASIGNATURAS:"Loading academic spaces",
      CARGANDO_PENSUMS:"Loading pensums",
      CARGANDO_AREAS:"Loading areas of SNIES",
      REGISTRANDO_AREA:"Registering area",
      CARGANDO_INFO_ACADEMICA: "Loading academic information",
      CARGANDO_PARAMETROS: "Loading parameterss",
      CARGANDO_TRANSACCION_REGISTRO: "Loading registration transaction",
      CARGANDO_SOLICITUDES_APROBADAS: "Loading approved requests",
      CARGANDO_TRABAJOS_DE_GRADO: "Loading degree works under postgraduate academic spaces modality",
      CARGANDO_PARAMETROS:"Loading parameterss",
      REGISTRANDO_RESPUESTAS:"Registering responses to applications for the admission process",
    },
    SELECT:{
      SELECCIONE:"Select an option",
      DOCENTE_CAMBIO: "Select the teacher to make the change",
      DOCENTE_REVISOR: "Select the project review teacher",
      DOCENTE_DIRECTOR: "Select the project director teacher",
      DOCENTE_REVISOR_FILTRO: "Enter at least 2 letters of the name of the project review teacher",
      DOCENTE_DIRECTOR_FILTRO: "Enter at least 2 letters of the name of the project director teacher",
      SIN_CARRERA:"No carreer selected",
      TIPO_DISTINCION:"Select the type of distinction",
      TRABAJO_GRADO_EVALUAR:"Select the degree job you want to evaluate",
      EVALUADOR_NUMERO:"Select the evaluator number {{numero}}",
      AREA_SNIES:"Select the SNIES area",
      NUCLEO_SNIES:"Select the basic core",
    },
    DOCUMENTO:{
        CARGAR_DOCUMENTO:"Load document",
        INGRESE_NOMBRE:"Enter the document's name",
        INGRESE_DESCRIPCION:"Enter the document's description",
        SELECCIONE_DOCUMENTO:"Select the document",
        SIN_DOCUMENTO:"There is not a selected document",
        SELECCIONAR_DOCUMENTO:"Select document",
        VER_DOCUMENTO:"View document",
        CARGADO:"Document loaded",
        INGRESE_CONSECUTIVO: "Enter the consecutive document",
    },
    SWITCH:{
        SI:"YES",
        NO:"NO",
    },
    CODIGO_MATERIA:"Subject code",
    SIN_CARRERAS_SOLICITUDES:"There are currently no carrers available for your choice",
    APROBAR_SOLICITUD:"Approve request",
    RECHAZAR_SOLICITUD:"Reject request",
    FORMULARIO_APROBACION:"Approval form",
    JUSTIFICACION_RESPUESTA_SOLICITUD:"Write the justification for the answer",
    ACTA_RESPUESTA_SOLICITUD:"Select the document with the answer given by the Career Council",
    RESPUESTA_SOLICITUD:"Response to the request",
    SOLICITUD_APROBADA:"The response to the request has been successfully registered",
    SOLICITAR_DISTINCION:"Want an application for this degree job",
    JUSTIFICACION_RESPUESTA:"Justification of the state.",
    AUTORIZACION_DERECHOS_AUTOR:"I <u> {{nombre}}</u> with code <u>{{codigo}}</u>, I express my desire to assign the copyright of the work of degree to the other related students.",
    SELECCIONE_ACTA:"Select the minutes by which the request is answered",
    SOLICITUD_CON_RESPUESTA:"The request has already been answered.",
    SOLICITUD_SIN_RESPUESTA:"The request has not been answered",
    RESULTADO_SOLICITUD:"Result of the request",
    SOLICITUD_RECHAZADA:"The request was rejected",
    SOLICITUD_ES_APROBADA:"The request was approved",
    SOLICITUD_OPCIONADA_SEGUNDA_CONVOCATORIA:"The application is optional for the second admission process.",
    SOLICITUD_RECHAZADA_CUPOS_INSUFICIENTES:"The application was rejected due to the availability of places in the postgraduate program.",
    SOLICITUD_APROBADA_EXENTA:"The application was approved free of charge, the student can formalize it.",
    INFORMACION_PRORROGA:"Important information about the extension",
    MENSAJE_PRORROGA:"Mr. student, you are informed that in accordance with the provisions of Agreement 038 of July 2015 issued by the academic council of the Francisco José de Caldas District University, you only have the right to an extension, that is, once you make this application regardless of the nature (extension to socialize or formalize) and is approved, you can not request it again.",
    APROBADO : {
        CURSAR_MODALIDAD: "The student can take the modality of {{modalidad}}",
        CANCELAR_MODALIDAD: "The student no longer attends the modality of {{modalidad}}",
        CAMBIAR_NOMBRE:"The name of the grade job '{{anterior}}' was changed to '{{nuevo}}'",
        DIRECTOR_INTERNO:"The internal director {{anterior}} was changed to {{nuevo}}",
        EVALUADOR:"The evaluator {{anterior}} was changed to {{nuevo}}",
        PRORROGA:"The requested extension is granted, therefore the student will not be able to request one again",
        CAMBIAR_MATERIA:"Subject {{anterior}} is changed to {{nuevo}}",
    },
    AREAS:{
        DATOS_AREA:"Data to register area",
        INGRESE_NOMBRE_AREA:"Enter the name of the new area",
        INGRESE_DESCRIPCION_AREA:"Enter the description of the area",
        REGISTRAR_AREA:"Register area",
        AREA_REGISTRADA:"The knowledge area was correctly registered",
        ERROR_REGISTRAR_AREA:"Could not register the area",
        AREA_EXISTENTE:"The knowledge area is already registered",
    },
    REGISTRO_EXITOSO:"Successful registration",
    DOCUMENTO_RESPUESTA_SOLICITUD:"Document with which the request was answered",
    EVALUADOR:"Evaluator(s)",
    DIRECTOR_INTERNO:"Internal director",
    ESPACIOS_ACADEMICOS_GUARDADOS:"Academic spaces saved",
    MENSAJE_ESPACIOS_ACADEMICOS_GUARDADOS:"The selected academic spaces can be chosen by the students to choose the modality of work of degree",
    MAS_ESPACIOS_ACADEMICOS:"Select more academic spaces",
    CREDITOS_ESPACIOS_ACADEMICOS_INSUFICIENTES:"The amount of credits of the academic spaces selected must be equal to or greater than {{creditos}} credits",
    ADMINISTRAR_AREAS:"Manage knowledge areas",
    SIN_AREAS:"Currently there are no registered areas of knowledge for this SNIES area",
    DESCRIPCION:"Description",
    NO_SOLICITUDES_POSGRADO:"There are no requests in the graduate academic spaces modality for the selected career",
    SELECCIONAR_PERIODO: "Select academic period",
    PASANTIA:{
      SOLICITAR_CARTA:"Request presentation's letter",
      INGRESE_NOMBRE_EMPRESA:"Enter the enterprise name",
      INGRESE_NOMBRE_DIRIGIDO:"Enter the name of the letter's recipient",
      INGRESE_CARGO_DIRIGIDO:"Enter the cargo of the letter's recipient",
      RECLAMAR_CARTA:"Mr. student note that once your request for a cover letter is approved you should go to pick it up at the internship office",
      SEGURO_INFORMACION_CARTA:"Mr. student, are you sure to request a letter addressed to Mr(s). {{nombre} who works as {{cargo}} in the company {{empresa}} ?, please verify all data."
    },
    ACEPTAR:"Accept",
    CANCELAR:"Cancel",
    FECHAS_PROCESO_MATERIAS_POSGRADO:"Dates of the process of the postgraduate subjects modality",
    FECHA_INICIO:"Start date",
    FECHA_FIN:"End date",
    FORMALIZAR_SOLICITUD: {
        TITULO: "Requests formalization",
        CONFIRMACION: "Confirmation to formalize the request selected",
        ACCION: "Formalize",
        MENSAJE_CONFIRMACION: "Are you sure you want to formalize the request {{idSolicitud}}, in the state {{nombreEstado}}, to study academic spaces in the postgraduate {{nombrePosgrado}}?",
        AVISO: "Request formalization",
        SOLICITUD_FORMALIZADA: "The request was formalized successfully",
        FECHAS_PARA_FORMALIZACION: "Valid dates to carry out the formalization process",
        FORMALIZACION_NO_HABILITADA: "The status of this request does not enable it to be formalized",
        REVISAR_FECHAS_FORMALIZACION: "Review the formalization periods, or contact the curricular project",
    },
    LISTAR_APROBADOS: {
        TITULO: "List of students admitted to the postgraduate",
        REGISTRAR: "Register",
        DESCRIPCION: "Selected request description",
        REGISTRAR_ESTUDIANTE: "Are you sure to register the student {{nombre}}, with student code {{codigo}}, in {{estado}} state, for the postgraduate subjects modality?",
        AVISO: "Approved request registration",
        ESTUDIANTE_REGISTRADO: "The modality for postgraduate academic spaces has been successfully registered",
    },
    REGISTRAR_NOTA: {
        TITULO: "Grades record in academic postgraduate spaces",
        CONFIRMACION: "Grades registration",
        MENSAJE_CONFIRMACION: "Are you sure of registering the grades entered for the academic spaces of the student {{nombre}}, with student code {{codigo}}?",
        AVISO: "Grades registration",
        NOTA_REGISTRADA: "The entered grades have been registered successfully.",
        DESCRIPCION: "Select degree work description",
        INSTRUCCIONES: "Input the grades obtained by the student by clicking on the corresponding cell. Keep in mind that valid grades range from 0.0 to 5.0, and two (2) decimals of accuracy will be taken for the record.",
    },
    PERIODO_ACADEMICO:"Academic period",
    SOLICITUD_NO_PUEDE_APROBARSE:"The request can not be approved",
    MATERIAS_POSGRADO:{
        CONFIRMACION_ADMITIR:"Confirmation of admitted",
        CONFIRMAR:"Pressing accept confirms that you want to execute the admission process with the selected students, this action can not be undone.",
        ADMITIDOS:"The following students will be admitted:",
        OPCIONADOS:"The following students will be eligible for the second call:",
        NO_ADMITIDOS:"The following students will not be admitted due to lack of quotas:",
        PROCESO_ADMISION_COMPLETO:"Admission process completed",
        RESPUESTAS_SOLICITUD:"The data of the admission process has been registered successfully",
    },
    NO_OPCIONES_DISPONIBLES:"No options available",
    ACCESO_NEGADO:"Access denied",
    ACCION_NO_DISPONIBLE:"Action not available",
};
angular.module('poluxClienteApp')
    .config(function($translateProvider) {
        $translateProvider
            .translations("es", text_es)
            .translations("en", text_en);
        $translateProvider.preferredLanguage("es");
        //$translateProvider.useSanitizeValueStrategy("sanitizeParameters");
        $translateProvider.useSanitizeValueStrategy("escaped");
    });
