'use strict';

/**
 * @ngdoc function
 * @name poluxClienteApp.decorator:TextTranslate
 * @description
 * # TextTranslate
 * Decorator of the poluxClienteApp
 */
var text_es = {
    TITULO: "GENERATOR-OAS",
    MENSAJE_INICIAL: "Ahora puede comenzar con el desarrollo ...",
    EVALUAR_PROYECTO: "Evaluación de Proyecto de Grado",
    LISTADO_SOLICITUD: "Listado de Solicitudes",
    MODALIDAD: "Modalidad",
    TITULO_PROPUESTA: "Título de la propuesta",
    VER_DOCUMENTO: "Ver documento",
    ESTADO_DOCUMENTO: "Estado Documento",
    RESUMEN: "Resumen",
    OPCIONES: "Opciones",
    SOLICITUD: "Solicitud",
    ASIGNAR_DOCENTE: "Asignar Docente",
    AREAS_CONOCIMIENTO: "Áreas de Conocimiento",
    LISTAR_SOLICITUDES: "Listado de solicitudes",
    ANO: "Año:",
    PERIODO: "Periodo:",
    CARRERA: "Carrera:",
    PENSUM: "Pensum:",
    SELECCIONAR_CARRERA: "*Seleccione la carrera",
    SELECCIONAR_PENSUM: "*Seleccione un pensum",
    CODIGO: "Código:",
    NOMBRE: "Nombre:",
    MODALIDAD_ESP_POS: "Modalidad: Espacios académicos de posgrado",
    ADMITIDOS_POR_RENDIMIENTO: "Admitidos por rendimiento:",
    ADMITIDOS_POR_ECONOMIA: "Admitidos por pago:",
    FECHA_ACTUAL: "Fecha actual:",
    FECHA_INICIO: "Primera fecha de inicio:",
    FECHA_INICIO_DOS: "Segunda fecha de inicio:",
    FECHA_FIN: "Fecha de finalización:",
    SELECCION_DE_ADMITIDOS: "Selección de Admitidos",
    ADMITIDOS_POR_EXCELENCIA_A: "Admitidos por excelencia académica y exentos de pago (Máx",
    ADMITIDOS_POR_COND_EC: "Admitidos admitidos por condiciones económicas y calidades académicas (Máx ",
    REQUERIDO: "Es requerido",
    PUBLICACION_DE_ESPACIOS: "Publicación de espacios académicos.",
    RESPUESTA: "Respuesta:",
    DENEGADO: "El estudiante no cumple con los requisitos exigidos para la Modalidad de Trabajo de Grado",
    REGISTRAR_PROPUESTA: "Registrar propuesta.",
    ESTADO: "Estado:",
    PORCENTAJE_CURSADO: "Porcentaje cursado",
    PROMEDIO: "Promedio",
    NIVEL_ESTUDIOS: "Nivel de estudios:",
    TIPO_CARRERA: "Tipo de carrera",
    REGISTRAR_TRABAJO_DE_GRADO: "Registrar trabajo de grado.",
    EDICION_FORMATO_EVALUACION: "Edición de Formatos de Evaluación",
    SELECCIONAR_FORMATO: "Seleccionar Formato:",
    EDICION_GENERAL: "Edición general",
    TITULO_FORMATO: "Titulo Formato:",
    INTRODUCCION: "Introducción:",
    EDICION_PREGUNTAS: "Edición Preguntas",
    ENUNCIADO: "Enunciado:",
    PESO: "Peso:",
    TIPO: "Tipo:",
    NUEVA_EVALUACION: "Nueva Evaluación",
    BUSCAR_FORMATOS: "Buscar Formatos",
    SELECCIONE_FORMATO: "Seleccione el formato",
    NOMBRE_FORMATO: "Nombre del formato",
    INTRODUCCION_FORMATO: "Introducción del formato",
    ANADIR_PREGUNTA: "Añadir Pregunta",
    ANADIR_OPCION: "Añadir Opción",
    VISTA_PREVIA: "Vista Previa",
    ASIGNAR_FORMATO_A_PC: "Asignar formato a proyecto curricular:",
    ASOCIAR_FORMATO_A_PC: "Asociar formato a proyecto curricular:",
    SELECCIONAR_PC: "Seleccionar proyecto curricular:",
    FECHA: "Fecha:",
    CREACION_EVALUACION: "Creación de la evaluación"




};
var text_en = {
    TITULO: "GENERATOR-OAS",
    MENSAJE_INICIAL: "Now get to start to develop",
    LISTADO_SOLICITUD: "List of Requests",
    MODALIDAD: "Modality",
    TITULO_PROPUESTA: "Title of proposal",
    VER_DOCUMENTO: "Show document",
    ESTADO_DOCUMENTO: "Document Status",
    RESUMEN: "Abstract",
    OPCIONES: "Options",
    SOLICITUD: "Request",
    ASIGNAR_DOCENTE: "Assign Teacher",
    AREAS_CONOCIMIENTO: "Knowledge Area",
    LISTAR_SOLICITUDES: "List of request",
    ANO: "Year:",
    PERIODO: "Term:",
    CARRERA: "Carrer:",
    PENSUM: "List of subjects:",
    SELECCIONAR_CARRERA: "*Select a carrer",
    SELECCIONAR_PENSUM: "*Select a list of subjects",
    CODIGO: "Code:",
    NOMBRE: "Name:",
    MODALIDAD_ESP_POS: "Modality: Postgraduate subjects",
    ADMITIDOS_POR_RENDIMIENTO: "Admited by academic performance:",
    ADMITIDOS_POR_ECONOMIA: "Admited by payment:",
    FECHA_ACTUAL: "Current date:",
    FECHA_INICIO: "Start date:",
    FECHA_INICIO_DOS: "Second start date:",
    FECHA_FIN: "Ending date:",
    SELECCION_DE_ADMITIDOS: "Selection of admitted students",
    ADMITIDOS_POR_EXCELENCIA_A: "Admitted by academic performance and no payment (Max",
    ADMITIDOS_POR_COND_EC: "Admitted by academic performance and payment (Max",
    REQUERIDO: "It's required",
    PUBLICACION_DE_ESPACIOS: "Announcement of subjects list.",
    RESPUESTA: "Answer:",
    DENEGADO: "The student doesn't Does not meet the requirements in order aply to this modality",
    REGISTRAR_PROPUESTA: "Register proposal.",
    ESTADO: "Status:",
    PORCENTAJE_CURSADO: "Percentage completed",
    PROMEDIO: "Average",
    NIVEL_ESTUDIOS: "Level of study:",
    TIPO_CARRERA: "Carrer type",
    REGISTRAR_TRABAJO_DE_GRADO: "Register graduation work.",
    EDICION_FORMATO_EVALUACION: "Edition of test formats",
    SELECCIONAR_FORMATO: "Select format:",
    EDICION_GENERAL: "General edition",
    TITULO_FORMATO: "Tittle of the format:",
    INTRODUCCION: "Introduction:",
    EDICION_PREGUNTAS: "Edition of questions",
    ENUNCIADO: "Statement:",
    PESO: "Value:",
    TIPO: "Type:",
    NUEVA_EVALUACION: "New test",
    BUSCAR_FORMATOS: "Search formats",
    SELECCIONE_FORMATO: "Select the format",
    NOMBRE_FORMATO: "Format name",
    INTRODUCCION_FORMATO: "Format introduction",
    ANADIR_PREGUNTA: "Add question",
    ANADIR_OPCION: "Add option",
    VISTA_PREVIA: "Preview",
    ASIGNAR_FORMATO_A_PC: "Asign format to a curricular project:",
    ASOCIAR_FORMATO_A_PC: "Asociate format to a curricular project:",
    SELECCIONAR_PC: "Select a curricular project",
    FECHA: "Date:",
    CREACION_EVALUACION: "Creation of the test",

};
angular.module('poluxClienteApp')
    .config(function($translateProvider) {
        $translateProvider
            .translations("es", text_es)
            .translations("en", text_en);
        $translateProvider.preferredLanguage("es");
        $translateProvider.useSanitizeValueStrategy("sanitizeParameters");
    });